### ISSUE TITLE
Support loading templates from git repos

### ISSUE THREAD

**Issue by countingtoten** [felix-cli/felix#10]
Add support for loading templates from the internet. The syntax should match `go get` as much as possible. Enable support for tags/branches.

**Acceptance Criteria**
- Load templates from remote git repos. ex: `felix -t github.com/felix-cli/grpc-service.felix init`
- Support tags and branches. ex: `felix -t github.com/felix-cli/grpc-service.felix@v1.0.0 init` `felix -t github.com/felix-cli/grpc-service.felix@test-branch init`

**Comment by scottcrawford03** [comment]
https://github.com/felix-cli/felix/pull/13
