### ISSUE TITLE
Update Readme :-)

### ISSUE THREAD

**Issue by arosales** [felix-cli/felix#2]
Suggest to update the readme to be **super easy** for folks to:

- What it is and what it does.
- Install
- An example to test things out
- Call to action for feedback

**Comment by scottcrawford03** [comment]
Awesome feed back, we will for sure do this. Do you have a list of all the commands you needed to run when you were trying to run it locally @arosales ?

**Comment by arosales** [comment]
I'll see if I can remember these or have them in my bash history. I'll post what I find.
